language: cpp

addons:
  apt:
    packages:
      - git
      - cmake

matrix:
  include:
    - os: osx
      compiler: g++-5
      env: COMPILER=g++ -std=c++14
    - os: linux
      compiler: g++-5
      env: COMPILER=g++ -std=c++14

before_script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt-get update;
      sudo apt-get install curl wget libssl-dev;
    else 
      brew install curl wget openssl;
    fi;

script:
  - mkdir build
  - cd build
  - cmake .. -DOPENSSL_ROOT_DIR=/usr/local/ssl -DOPENSSL_LIBRARIES=/usr/local/ssl/lib && make
  - ./tests
